/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as HireRouteImport } from './routes/hire'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CareersIndexRouteImport } from './routes/careers.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as InsightsSlugRouteImport } from './routes/insights.$slug'
import { Route as CaseStudiesPryvaseeAiRouteImport } from './routes/case-studies/pryvasee-ai'
import { Route as CareersRoleIdRouteImport } from './routes/careers.$roleId'
import { Route as CareersRoleIdIndexRouteImport } from './routes/careers.$roleId.index'
import { Route as CareersRoleIdApplyRouteImport } from './routes/careers.$roleId.apply'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const HireRoute = HireRouteImport.update({
  id: '/hire',
  path: '/hire',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersIndexRoute = CareersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CareersRoute,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)
const InsightsSlugRoute = InsightsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => InsightsRoute,
} as any)
const CaseStudiesPryvaseeAiRoute = CaseStudiesPryvaseeAiRouteImport.update({
  id: '/case-studies/pryvasee-ai',
  path: '/case-studies/pryvasee-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoleIdRoute = CareersRoleIdRouteImport.update({
  id: '/$roleId',
  path: '/$roleId',
  getParentRoute: () => CareersRoute,
} as any)
const CareersRoleIdIndexRoute = CareersRoleIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CareersRoleIdRoute,
} as any)
const CareersRoleIdApplyRoute = CareersRoleIdApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => CareersRoleIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRouteWithChildren
  '/contact': typeof ContactRoute
  '/hire': typeof HireRoute
  '/insights': typeof InsightsRouteWithChildren
  '/services': typeof ServicesRouteWithChildren
  '/careers/$roleId': typeof CareersRoleIdRouteWithChildren
  '/case-studies/pryvasee-ai': typeof CaseStudiesPryvaseeAiRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/careers/': typeof CareersIndexRoute
  '/careers/$roleId/apply': typeof CareersRoleIdApplyRoute
  '/careers/$roleId/': typeof CareersRoleIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/hire': typeof HireRoute
  '/insights': typeof InsightsRouteWithChildren
  '/services': typeof ServicesRouteWithChildren
  '/case-studies/pryvasee-ai': typeof CaseStudiesPryvaseeAiRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/careers': typeof CareersIndexRoute
  '/careers/$roleId/apply': typeof CareersRoleIdApplyRoute
  '/careers/$roleId': typeof CareersRoleIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRouteWithChildren
  '/contact': typeof ContactRoute
  '/hire': typeof HireRoute
  '/insights': typeof InsightsRouteWithChildren
  '/services': typeof ServicesRouteWithChildren
  '/careers/$roleId': typeof CareersRoleIdRouteWithChildren
  '/case-studies/pryvasee-ai': typeof CaseStudiesPryvaseeAiRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/careers/': typeof CareersIndexRoute
  '/careers/$roleId/apply': typeof CareersRoleIdApplyRoute
  '/careers/$roleId/': typeof CareersRoleIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/hire'
    | '/insights'
    | '/services'
    | '/careers/$roleId'
    | '/case-studies/pryvasee-ai'
    | '/insights/$slug'
    | '/services/$slug'
    | '/careers/'
    | '/careers/$roleId/apply'
    | '/careers/$roleId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/hire'
    | '/insights'
    | '/services'
    | '/case-studies/pryvasee-ai'
    | '/insights/$slug'
    | '/services/$slug'
    | '/careers'
    | '/careers/$roleId/apply'
    | '/careers/$roleId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/hire'
    | '/insights'
    | '/services'
    | '/careers/$roleId'
    | '/case-studies/pryvasee-ai'
    | '/insights/$slug'
    | '/services/$slug'
    | '/careers/'
    | '/careers/$roleId/apply'
    | '/careers/$roleId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CareersRoute: typeof CareersRouteWithChildren
  ContactRoute: typeof ContactRoute
  HireRoute: typeof HireRoute
  InsightsRoute: typeof InsightsRouteWithChildren
  ServicesRoute: typeof ServicesRouteWithChildren
  CaseStudiesPryvaseeAiRoute: typeof CaseStudiesPryvaseeAiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire': {
      id: '/hire'
      path: '/hire'
      fullPath: '/hire'
      preLoaderRoute: typeof HireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/': {
      id: '/careers/'
      path: '/'
      fullPath: '/careers/'
      preLoaderRoute: typeof CareersIndexRouteImport
      parentRoute: typeof CareersRoute
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/insights/$slug': {
      id: '/insights/$slug'
      path: '/$slug'
      fullPath: '/insights/$slug'
      preLoaderRoute: typeof InsightsSlugRouteImport
      parentRoute: typeof InsightsRoute
    }
    '/case-studies/pryvasee-ai': {
      id: '/case-studies/pryvasee-ai'
      path: '/case-studies/pryvasee-ai'
      fullPath: '/case-studies/pryvasee-ai'
      preLoaderRoute: typeof CaseStudiesPryvaseeAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/$roleId': {
      id: '/careers/$roleId'
      path: '/$roleId'
      fullPath: '/careers/$roleId'
      preLoaderRoute: typeof CareersRoleIdRouteImport
      parentRoute: typeof CareersRoute
    }
    '/careers/$roleId/': {
      id: '/careers/$roleId/'
      path: '/'
      fullPath: '/careers/$roleId/'
      preLoaderRoute: typeof CareersRoleIdIndexRouteImport
      parentRoute: typeof CareersRoleIdRoute
    }
    '/careers/$roleId/apply': {
      id: '/careers/$roleId/apply'
      path: '/apply'
      fullPath: '/careers/$roleId/apply'
      preLoaderRoute: typeof CareersRoleIdApplyRouteImport
      parentRoute: typeof CareersRoleIdRoute
    }
  }
}

interface CareersRoleIdRouteChildren {
  CareersRoleIdApplyRoute: typeof CareersRoleIdApplyRoute
  CareersRoleIdIndexRoute: typeof CareersRoleIdIndexRoute
}

const CareersRoleIdRouteChildren: CareersRoleIdRouteChildren = {
  CareersRoleIdApplyRoute: CareersRoleIdApplyRoute,
  CareersRoleIdIndexRoute: CareersRoleIdIndexRoute,
}

const CareersRoleIdRouteWithChildren = CareersRoleIdRoute._addFileChildren(
  CareersRoleIdRouteChildren,
)

interface CareersRouteChildren {
  CareersRoleIdRoute: typeof CareersRoleIdRouteWithChildren
  CareersIndexRoute: typeof CareersIndexRoute
}

const CareersRouteChildren: CareersRouteChildren = {
  CareersRoleIdRoute: CareersRoleIdRouteWithChildren,
  CareersIndexRoute: CareersIndexRoute,
}

const CareersRouteWithChildren =
  CareersRoute._addFileChildren(CareersRouteChildren)

interface InsightsRouteChildren {
  InsightsSlugRoute: typeof InsightsSlugRoute
}

const InsightsRouteChildren: InsightsRouteChildren = {
  InsightsSlugRoute: InsightsSlugRoute,
}

const InsightsRouteWithChildren = InsightsRoute._addFileChildren(
  InsightsRouteChildren,
)

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CareersRoute: CareersRouteWithChildren,
  ContactRoute: ContactRoute,
  HireRoute: HireRoute,
  InsightsRoute: InsightsRouteWithChildren,
  ServicesRoute: ServicesRouteWithChildren,
  CaseStudiesPryvaseeAiRoute: CaseStudiesPryvaseeAiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
